#!/usr/bin/env sh

# Start the README with a warning message that it's machine generated
cat > README.md <<- END
<!-- This file is automatically generated! -->
<!-- Do not manually edit! To make changes, see build_readme.sh instead. -->

END

# Add a dynamic button to run this project on binder
cat >> README.md <<- END
# Getting Started
Click this button [![Binder](https://mybinder.org/badge_logo.svg)](`git config --get remote.origin.url`/HEAD) to run this project!

You'll find everything you need in \`main.ipynb\`!

# Files in this Project

- TODO

# Making Edits
Changes that you make on binder are temporary. You can download your files from binder, or you can make your own repo that lives on github.

To make your own repo copy of this project that you can edit:

1. Create a [copy of this template](`git config --get remote.origin.url`/generate). It will need to be a public repo, but you can name it whatever you want
2. Create a [github personal access token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token). It will need the \`repo\` and \`workflow\` scopes
3. Open your project on binder (the binder button in your README will automatically update to link to your project!)
4. Make edits to your project on binder like you normally would
5. Open a terminal on binder and run:
\`\`\`sh
git pull
git add --all
git commit -m "some friendly message here"
git push
\`\`\`
When prompted to enter your password, enter your personal access token instead.

END
